Repository xxlo-devs/eru, pull requests merged in 2020-09, with the labels that each got.

#72 Fix the bug from issue #68
  src/eru.WebApp/Pages/Upload.cshtml
  src/eru.WebApp/wwwroot/js/upload.js
Labels: bug

#80 Update LICENSE
  LICENSE
Labels: documentation

#95 Feature/docker
  .dockerignore
  .github/workflows/main-pipeline.yml
  .github/workflows/tests.yml
  Dockerfile
  README.md
  docs/config.md
  docs/docker.md
  mkdocs.yml
  src/eru.Application/eru.Application.csproj
  src/eru.Infrastructure/eru.Infrastructure.csproj
  src/eru.WebApp/appsettings.docker.json
  src/eru.WebApp/eru.WebApp.csproj
Labels: deployment

#102 Docs update
  README.md
  docs/build-from-source.md
  docs/config.md
  docs/index.md
  mkdocs.yml
Labels: documentation
